# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7
    - name: Setup packages
      run: pip install pipenv && ls -la && pipenv install
    - name: Run tests
      run: pytest .
