name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0

    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7

    - name: Setup packages and run tests
      run: |
        pip install pipenv
        pipenv install
        pipenv run pytest . --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: e480b629874f76fa35ebcbe37f26840c1a5f07ab877c45bbe0baf5431f1b2856
      coverageCommand: echo 'pass'
      coverageLocations: ./coverage.xml
